### PR TITLE
shot in the dark

### PR DESCRIPTION
**Pull request by nicholassewitz**
I'm trying to make the summary for subscriptions show the month. Right now when you do /apr summary subscriptions it shows you the subscriptions activated today.

Also down the road im trying to group everything by month so when you subscribe to subscriptions in a channel it shows you a count of subscriptions but I believe its showing you all subscriptions not just the first subscription. We are trying to only show the count of first subscriptions. @izakp 

```
:moneybag: SOCO GALLERY's subscription activated
Outreach Admin
----------------
Melanie Edmunds

Total this month
----------------
192
```

### CODE REVIEW

**Comment by izakp** [comment]
@nicholassewitz what is this intended to fix?

**Comment by nicholassewitz** [comment]
I'm trying to make the summary for subscriptions show the month. Right now when you do `/apr summary subscriptions` it shows you the subscriptions activated today.

Also down the road im trying to group everything by month so when you subscribe to subscriptions in a channel it shows you a count of subscriptions but I believe its showing you all subscriptions not just the first subscription. We are trying to only show the count of first subscriptions. @izakp  https://cl.ly/1h1z0W0w0r2U

**Comment by nicholassewitz** [comment]
sorry i didn't realize this made it so far along in git. i would have added a subscriptions

**Comment by ashkan18** [comment]
So we want to only show first subscriptions per month right?

**Comment by nicholassewitz** [comment]
correct

**Comment by ashkan18** [comment]
closing in favor of https://github.com/artsy/aprb/pull/79

**Pull request closed without merging**
