### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by ashkan18**
This is a whole lot simpler Docker setup compared to APR mainly since we are not using Phoenix which means no need for setting up npm, also no Websocket, so I think we don't even need nginx proxy setup.

### CODE REVIEW

**Comment by izakp** [comment]
@ashkan18 please have a look at https://github.com/artsy/APR/blob/master/Dockerfile - we need to do all those additional build steps as well

**Comment by izakp** [comment]
@ashkan18 also please add a https://github.com/artsy/APR/blob/master/kubernetes.yml

**Comment by ashkan18** [comment]
@izakp we don't need those things in APR's Dockerfile since it's not a Phoenix app 💃

**Comment by izakp** [comment]
👍

**Pull request merged**
