### PR TITLE
Downscale APRB

### PR DESCRIPTION
**Pull request by ashkan18**
# Problem
We are currently running with two pods, but since this is relatively small app and not many calls into it, going to scale it down to 1 pod. 

People say Elixir is really efficient when it comes to using resources, I believe that and going to trust it :)

# Migration
```
hokusai production update
```

### CODE REVIEW

**Comment by ashkan18** [comment]
ran the migration 👍

**Comment by izakp** [comment]
Okay if you are happy with brief downtime when we need to rotate nodes out for new one.

Once caveat is that a deployment with 1 replica will block autoscaling for the node on which the single pod is running, as the cluster autoscaler is [configured to only shuffle pods around for any deployment that has a min of 2 replicas](https://github.com/artsy/substance/blob/master/clusters/production/federation/kubernetes-production-orion.artsy.systems/services/cluster-autoscaler.yml#L151) cc @joeyAghion

**Comment by joeyAghion** [comment]
> a deployment with 1 replica will block autoscaling...

Good point! Will 1-pod deployment be placed on the "fixed" capacity in an intelligent way, or might this put us in a weird position where no pods can be scaled down?

**Comment by dleve123** [comment]
For my own knowledge, what’s the cost of having 1 versus 2 versus N number of pods running? Is each pod given a fixed memory allocation? If so, could someone show me where that lives for a given project?

**Comment by izakp** [comment]
> Good point! Will 1-pod deployment be placed on the "fixed" capacity in an intelligent way, or might this put us in a weird position where no pods can be scaled down?

Not unless it requests to be scheduled on fixed capacity nodes like [gravity does](https://github.com/artsy/gravity/blob/master/hokusai/production.yml#L57) via `affinity` specifying `tier=api` nodes

**Comment by izakp** [comment]
> For my own knowledge, what’s the cost of having 1 versus 2 versus N number of pods running? Is each pod given a fixed memory allocation? If so, could someone show me where that lives for a given project?

See https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

For our projects using Hokusai, look for staging configuration in the `./hokusai/staging.yml` file and production configuration in the `./hokusai/production.yml` file

An application can make resource requests and optionally, set hard limits via the `resources` config block (see [Gravity's production configuration](https://github.com/artsy/gravity/blob/master/hokusai/production.yml#L41)).

If requests / limits aren't specified, Kubernetes reverts to [these default limits](https://github.com/artsy/substance/blob/master/services/limits.yml#L8) configured in the namespace's LimitRange.

The advantage to running > 1 replicas is for redundancy as some nodes are in autoscaling configuration go in and out of service (as well as providing high availability during deployments / node failure and while performing cluster maintenance).

**Pull request merged**
