### PR TITLE
@izakp => Fix: CI badges [ci skip]

### PR DESCRIPTION
**Pull request by dblock**

### CODE REVIEW

**Comment by dblock** [comment]
Note that build is failing. It seems that it's trying to deploy my PR? That shouldn't happen I imagine :)

**Comment by ashkan18** [comment]
@dblock it's trying to update the image on ECR, it should only do this once it's merged to `master`, I'll take a look.

**Comment by ashkan18** [comment]
I was wrong, it's actually not on updating the image on ECR, it's on creating docker image step. I think we still want to do that for PRs to make sure container an still be built. I think current ci setup is missing `AWS_ACCOUNT_ID` I'll add that.

**Comment by dblock** [comment]
@ashkan18 It's green! I'll merge.

**Pull request merged**
