### PR TITLE
updates for Hokusai v1.0-beta

### PR DESCRIPTION
**Pull request by izakp**
Updates environment and label selectors for Hokusai v1.0-beta.

Migration:

1. Create new environment by merging config and secrets

```
kubectl config use-context staging
kubectl get configmap aprb-config -o json | jq -r '.data | keys[] as $k | "\($k)=\(.[$k])"' >> migration.env
kubectl get secret aprb-secrets -o json | jq -r '.data | keys[] as $k | "\($k) \(.[$k])"' | awk '{ "echo "$2" | base64 --decode" | getline x; print $1,x }' | sed -e 's/ /=/g' >> migration.env
hokusai env create --staging
hokusai env set $(cat migration.env | tr '\n' ' ') --staging
```

2. Update staging stack: hokusai stack update --staging

3. Get new ELB address for aprb-web from hokusai stack status --staging and add to DYN

4. Delete old aprb k8s objects:

```
kubectl delete service aprb
kubectl delete deployment aprb
kubectl delete configmap aprb-config
kubectl delete secret aprb-secrets
```

### CODE REVIEW

**Comment by ashkan18** [comment]
Thanks @izakp for cleaning this up.

**Comment by ashkan18** [comment]
as for migration, should we do it in production first and then `promote`? or first promote and then run migration?

**Comment by izakp** [comment]
@ashkan18 you should try the above steps on staging first... then repeat on production - no promotion needed as this is not changing the image tag

**Comment by ashkan18** [comment]
finished this on staging, also as a sidenote, the DNS change had to happen in Route 53 in Amazon since aprb is under artsy.systems now.

**Comment by izakp** [comment]
@ashkan18 👍

**Comment by izakp** [comment]
@ashkan18 also applied to production

**Comment by ashkan18** [comment]
thanks @izakp ! did you promote staging too?

**Comment by izakp** [comment]
@ashkan18 nope this was just stack updates - you can promote to the latest release if you like

**Pull request merged**
